import { type RouteConfig, index, route } from "@react-router/dev/routes";
export default [
  route("api/*", "routes/preview-api.ts"),
  index("routes/home.tsx"),
  route("shop", "routes/shop.tsx"),
  route("collections", "routes/collections.tsx"),
  route("collections/:slug", "routes/collection.tsx"),
  route("materials", "routes/materials.tsx"),
  route("about", "routes/about.tsx"),
  route("care", "routes/care.tsx"),
  route("products/:slug", "routes/product.tsx"),
  route("our-craft", "routes/craft.tsx"),
  route("bulk-orders", "routes/bulk.tsx"),
  route("wishlist", "routes/wishlist.tsx"),
  route("cart", "routes/cart.tsx"),
  route("checkout", "routes/checkout.tsx"),
  route("account", "routes/account.tsx"),
  route("account/link", "routes/account-link.tsx"),
  route("preferences", "routes/preferences.tsx"),
  route("contact", "routes/contact.tsx"),
  route("track-order", "routes/tracking.tsx"),
  route("orders/:reference", "routes/order.tsx"),
  route("quotes/:id", "routes/quote.tsx"),
  route("journal", "routes/journal.tsx"),
  route("journal/:slug", "routes/article.tsx"),
  route("admin", "routes/admin.tsx"),
  route("cms", "routes/cms.tsx"),
  route(":page", "routes/info.tsx"),
  route("*", "routes/not-found.tsx"),
] satisfies RouteConfig;
