import type { Product } from "../app/lib/catalog.ts";

/* Placeholder listings so the shop has something to show before real stock is
   entered. Prices are in minor units (paise / cents / pence). Every SKU starts
   with SAMPLE- so these are easy to spot — they are never written to the
   database. getProducts() returns them only in the design preview, or in
   development while the products collection is still empty. */
type Sample = Omit<
  Product,
  "status" | "gallery" | "leadTime" | "sku" | "styleCode"
> & { code: string };

const samples: Sample[] = [
  {
    code: "URN-001",
    id: "sample-cypress-urn",
    slug: "cypress-urn",
    name: "Cypress Urn",
    subtitle: "Pearl enamel with a gold-toned band",
    category: "urns",
    material: "Brass & enamel",
    finish: "Pearl white, gold band",
    image: "catalogue/urns/cypress-urn-1",
    prices: { INR: 3850000, USD: 46000, GBP: 36000, EUR: 42000 },
    description:
      "A lidded urn in pearl-white enamel with an engraved gold-toned band at the shoulder and foot. Threaded lid, felt-lined base and room for hand engraving to order.",
    dimensions: "H 28 cm × Ø 17 cm",
    weight: "2.1 kg",
    stock: 6,
    featured: true,
    care: "Dust with a dry cloth. Avoid abrasive cleaners on the enamel.",
  },
  {
    code: "URN-002",
    id: "sample-reliquary-urn",
    slug: "reliquary-urn",
    name: "Reliquary Urn",
    subtitle: "Silver-plated brass, heart motif",
    category: "urns",
    material: "Silver-plated brass",
    finish: "Antiqued",
    image: "catalogue/urns/reliquary-urn-2",
    prices: { INR: 5200000, USD: 62000, GBP: 49000, EUR: 57000 },
    description:
      "A white-enamel urn banded in antiqued silver-plated brass, with a pierced heart motif on the front. Sealed, threaded lid; hand engraving available to order.",
    dimensions: "H 30 cm × Ø 19 cm",
    weight: "3.4 kg",
    stock: 3,
    featured: false,
    care: "Wipe with a soft dry cloth. Do not use metal polish on plated surfaces.",
  },
  {
    code: "LGT-001",
    id: "sample-soleil-lamp",
    slug: "soleil-table-lamp",
    name: "Soleil Table Lamp",
    subtitle: "Blue-and-white ceramic with polished brass",
    category: "lighting",
    material: "Ceramic & brass",
    finish: "Polished brass",
    image: "catalogue/lighting/soleil-lamp-1",
    prices: { INR: 1650000, USD: 19900, GBP: 15500, EUR: 18000 },
    description:
      "A hand-painted blue-and-white ceramic base set in polished brass, wired and balanced by hand and finished with a pleated shade. Dimmable fitting, fine cloth flex.",
    dimensions: "H 58 cm × Ø 38 cm",
    weight: "3.8 kg",
    stock: 12,
    featured: true,
    care: "Dust the shade with a soft brush. Wipe the brass with a dry cloth only.",
  },
  {
    code: "LGT-002",
    id: "sample-halo-lamp",
    slug: "halo-table-lamp",
    name: "Halo Table Lamp",
    subtitle: "Hand-painted ceramic with brass fittings",
    category: "lighting",
    material: "Ceramic & brass",
    finish: "Hand-painted",
    image: "catalogue/lighting/halo-lamp-2",
    prices: { INR: 1980000, USD: 23900, GBP: 18800, EUR: 21900 },
    description:
      "A patterned ceramic base in deep blue with brass fittings and a pleated linen-style shade. Wired and balanced by hand, with a dimmable fitting.",
    dimensions: "H 52 cm × Ø 32 cm",
    weight: "3.1 kg",
    stock: 8,
    featured: false,
    care: "Dust the shade with a soft brush. Wipe the base with a dry cloth.",
  },
  {
    code: "KIT-001",
    id: "sample-arbor-serveware",
    slug: "arbor-serving-set",
    name: "Arbor Serving Set",
    subtitle: "Silver-plated brass, in a presentation box",
    category: "kitchenware",
    material: "Silver-plated brass",
    finish: "Mirror-polished",
    image: "catalogue/kitchenware/arbor-service-5",
    prices: { INR: 920000, USD: 11000, GBP: 8700, EUR: 10200 },
    description:
      "A silver-plated brass serving set presented in a velvet-lined gift box. Made for gifting, and for tables that deserve a little ceremony.",
    dimensions: "Box 34 × 24 × 10 cm",
    weight: "1.8 kg",
    stock: 20,
    featured: false,
    care: "Keep in the box when not in use. Wipe with a soft cloth; no abrasive polish.",
  },
  {
    code: "DEC-001",
    id: "sample-teardrop-vessel",
    slug: "teardrop-vase-pair",
    name: "Teardrop Vase Pair",
    subtitle: "A pair of spun brass vases",
    category: "decor",
    material: "Hand-spun brass",
    finish: "Polished brass",
    image: "catalogue/decor/teardrop-vessel-1",
    prices: { INR: 2450000, USD: 29500, GBP: 23000, EUR: 27000 },
    description:
      "A pair of teardrop vases spun from brass and polished to a warm gold. Display them together or apart, with a single stem or on their own.",
    dimensions: "H 34 / 28 cm",
    weight: "1.9 kg (pair)",
    stock: 2,
    featured: true,
    care: "Wipe with a soft dry cloth. A little brass polish restores the shine if needed.",
  },
  {
    code: "DEC-002",
    id: "sample-rosa-vessel",
    slug: "rosa-vase-pair",
    name: "Rosa Vase Pair",
    subtitle: "A pair of satin brass vases",
    category: "decor",
    material: "Hand-spun brass",
    finish: "Satin brass",
    image: "catalogue/decor/rosa-vessel-4",
    prices: { INR: 1380000, USD: 16500, GBP: 13000, EUR: 15200 },
    description:
      "A matched pair of slim brass vases with a softly brushed satin finish and a gently flared neck. Quiet, tactile and made to sit side by side.",
    dimensions: "H 26 / 22 cm",
    weight: "1.4 kg (pair)",
    stock: 0,
    featured: false,
    care: "Wipe with a soft dry cloth. Avoid abrasive cleaners on the satin finish.",
  },
  {
    code: "ACC-001",
    id: "sample-meridian-globe",
    slug: "meridian-globe",
    name: "Meridian Globe",
    subtitle: "Silver-toned, on a clear acrylic base",
    category: "accessories",
    material: "Brass & enamel",
    finish: "Hand-polished",
    image: "catalogue/accessories/meridian-globe-1",
    prices: { INR: 1120000, USD: 13500, GBP: 10600, EUR: 12400 },
    description:
      "A desk-sized world globe in a silver-toned finish, set on a clear acrylic base. Gift-boxed and made to be turned over in the hand.",
    dimensions: "H 30 cm × Ø 20 cm",
    weight: "1.6 kg",
    stock: 15,
    featured: false,
    care: "Dust with a soft cloth. Avoid abrasive cleaners on the surface.",
  },
];

export const sampleProducts: Product[] = samples.map(
  ({ code, ...product }) => ({
    ...product,
    status: "published",
    sku: `SAMPLE-${code}`,
    styleCode: code,
    leadTime: "Ships in 5–7 working days",
    gallery: [],
  }),
);
